theme: jekyll-theme-minimal
title: Multi-Platform Chat Music Queue System
description: Çok platformlu sohbet üzerinden müzik kuyruk sistemi (Kick, YouTube, radyo vb.)
logo: https://avatars.githubusercontent.com/u/96188887?v=4
show_downloads: true
github_url: https://github.com/eoatsey/Multi-Platform-Chat-Music-Queue-System
